import React from "react";

export const CodeDtlTableColumns = () => {
  return [
    {
      Header: "분류코드",
      accessor: "cdField",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "CODE",
      accessor: "cdSysdef",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME",
      accessor: "nmSysdef",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(EN)",
      accessor: "nmSysdefEn",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L1)",
      accessor: "nmSysdefL1",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L2)",
      accessor: "nmSysdefL2",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L3)",
      accessor: "nmSysdefL3",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L4)",
      accessor: "nmSysdefL4",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L5)",
      accessor: "nmSysdefL5",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "USER CODE",
      accessor: "cdUsrdef",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "USER NM",
      accessor: "nmUsrdef",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "USER NM(EN)",
      accessor: "nmUsrdefEn",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "USER NM(L1)",
      accessor: "nmUsrdefL1",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "USER NM(L2)",
      accessor: "nmUsrdefL2",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "SORT",
      accessor: "noOrder",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "USE",
      accessor: "useYn",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 50,
      maxWidth: 100,
      editable: true,
      type: "checkbox",
      options: [
        { value: "0", label: "N" },
        { value: "1", label: "Y" },
      ],
    },
  ];
};
