import React from "react";

export const CodeTableColumns = () => {
  return [
    {
      Header: "CODE",
      accessor: "cdField",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME",
      accessor: "nmField",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(EN)",
      accessor: "nmFieldEn",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(JP)",
      accessor: "nmFieldJp",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L1)",
      accessor: "nmFieldL1",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L2)",
      accessor: "nmFieldL2",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L3)",
      accessor: "nmFieldL3",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L4)",
      accessor: "nmFieldL4",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "NAME(L5)",
      accessor: "nmFieldL5",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
    {
      Header: "REMARK",
      accessor: "remark",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 100,
      width: 150,
      maxWidth: 210,
      type: "text",
      editable: true,
    },
  ];
};
