export const SalesOrderTableColumns = () => {
  return [
    {
      Header: "ORDER",
      columns: [
        {
          Header: "Buyer",
          accessor: "nmBuyer",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          editable: true,
          isSearchBtn: true,
        },
        {
          Header: "BRAND",
          accessor: "nmBrand",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          editable: true,
          isSearchBtn: true,
        },
        {
          Header: "Style",
          accessor: "noStyle",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          type: "text",
          editable: true,
          isSearchBtn: true,
        },
        {
          Header: "ITEM",
          accessor: "nmItem",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          type: "text",
          editable: true,
          isSearchBtn: true,
        },
        {
          Header: "수량",
          accessor: "quantity",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          type: "text",
          editable: true,
          number: true,
        },
        {
          Header: "금액",
          accessor: "amount",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          type: "text",
          editable: true,
          number: true,
        },
        {
          Header: "참고사항",
          accessor: "remarks",
          sort: true,
          flexGrow: 1,
          flexShrink: 1,
          type: "text",
          editable: true,
        },
      ],
    },
  ];
};
