import React from "react";

export const SalesActivityTableColumns = () => {
  // <br>태그 공백 제거 함수
  const renderTextWithoutBr = (value: any) => {
    return String(value || "").replace(/<br\s*\/?>/gi, "");
  };
  return [
    {
      Header: "SEQ",
      accessor: "lvlFig",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      sort: true,
      minWidth: 60,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "상담일자",
      accessor: "dtMeeting",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 100,
      width: 100,
      maxWidth: 1000,
    },
    {
      Header: "진행",
      accessor: "gwStatus",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "담당자",
      accessor: "nmEmp",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 100,
      width: 100,
      maxWidth: 1000,
    },
    {
      Header: "부서명",
      accessor: "nmDept",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 120,
      maxWidth: 1000,
    },
    {
      Header: "DOCU#",
      accessor: "noDocu",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "업무구분",
      accessor: "nmWork",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 100,
      width: 100,
      maxWidth: 1000,
    },
    {
      Header: "상세분류",
      accessor: "nmDetail",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "상담목적",
      accessor: "purpose",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "상담유형",
      accessor: "nmActivity",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "회사",
      accessor: "nmVendor",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "본사참석자",
      accessor: "descAttend",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "업체상담자(연락처)",
      accessor: "nmNameVendor",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "Agenda",
      accessor: "agenda",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "결과및기대효과",
      accessor: "results",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "향후계획(Follow Up)",
      accessor: "progress",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "Buyer",
      accessor: "nmBuyer",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "BRAND",
      accessor: "nmBrand",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "ITEM",
      accessor: "nmItem",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "수량",
      accessor: "quantity",
      sort: true,
      className: "text-end",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 80,
      width: 80,
      maxWidth: 1000,
    },
    {
      Header: "금액",
      accessor: "amount",
      sort: true,
      className: "text-end",
      Cell: ({ value }: { value: any }) => (
        <div
          style={{ fontWeight: "normal", whiteSpace: "pre-line", display: "block" }}
          dangerouslySetInnerHTML={{
            __html: (value || "").replace(/<\/?br\s*\/?>/g, "<br />"),
          }}
        />
      ),
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
    {
      Header: "키워드",
      accessor: "keywords",
      sort: true,
      className: "text-left",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{renderTextWithoutBr(value)}</span>,
      minWidth: 120,
      width: 150,
      maxWidth: 1000,
    },
  ];
};
