import React from "react";

export const ProgramTableColumns = (onRemoveNewRow: (index: number) => void) => {
  return [
    {
      Header: "메뉴화면정보",
      columns: [
        {
          Header: "NO",
          accessor: "seqNo",
          Cell: ({ row }: { row: any }) => (
            <span
              style={{
                fontWeight: "normal",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              {row.original.isNew ? (
                <button onClick={() => onRemoveNewRow(row.index)} className={"delete-table-table-row"}>
                  X
                </button>
              ) : (
                row.original.seqNo
              )}
            </span>
          ),
          sort: true,
          minWidth: 40,
          width: 40,
          maxWidth: 100,
        },
        {
          Header: "NAME(KO)",
          accessor: "pageNameKo",
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          sort: true,
          minWidth: 100,
          width: 150,
          maxWidth: 210,
          type: "text",
          editable: true,
        },
        {
          Header: "NAME(EN)",
          accessor: "pageNameEn",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 100,
          width: 150,
          maxWidth: 210,
          type: "text",
          editable: true,
        },
        {
          Header: "NAME(VN)",
          accessor: "pageNameVn",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 100,
          width: 150,
          maxWidth: 210,
          type: "text",
          editable: true,
        },
        {
          Header: "MENU",
          accessor: "menuId",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 80,
          width: 130,
          maxWidth: 180,
          type: "text",
          editable: true,
        },
        {
          Header: "PARENT",
          accessor: "parentNo",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 80,
          width: 80,
          maxWidth: 100,
          type: "text",
          editable: true,
        },
        {
          Header: "TYPE",
          accessor: "menuType",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 60,
          maxWidth: 100,
          type: "text",
          editable: true,
        },
        {
          Header: "LEVEL",
          accessor: "menuLevel",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 60,
          maxWidth: 100,
          type: "text",
          editable: true,
        },
        {
          Header: "SORT",
          accessor: "sortNo",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 60,
          maxWidth: 100,
          type: "text",
          editable: true,
        },
        {
          Header: "URL",
          accessor: "pageUrl",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 60,
          width: 80,
          maxWidth: 160,
          type: "text",
          editable: true,
        },
        {
          Header: "PREFIX",
          accessor: "pagePrefix",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 60,
          maxWidth: 100,
          type: "text",
          editable: true,
        },
      ],
    },
    {
      Header: "버튼권한설정",
      columns: [
        {
          Header: "USE",
          accessor: "useYn",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 50,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "PAGE",
          accessor: "pageYn",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 50,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "FIND",
          accessor: "find",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 50,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "NEW",
          accessor: "newFlag",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 50,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "DELETE",
          accessor: "del",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 60,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "SAVE",
          accessor: "sav",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 50,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "PRINT",
          accessor: "prt",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 50,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "EXCELDOWN",
          accessor: "excelDown",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 80,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
        {
          Header: "EXCELUPLOAD",
          accessor: "excelUp",
          sort: true,
          Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
          minWidth: 40,
          width: 80,
          maxWidth: 100,
          editable: true,
          type: "checkbox",
          options: [
            { value: "0", label: "N" },
            { value: "1", label: "Y" },
          ],
        },
      ],
    },
  ];
};
