import React from "react";
const formatYYYYMMDD = (v?: string | number) => {
  if (!v) return "";
  const s = String(v);
  if (s.length !== 8) return s; // 예외 방어
  return `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}`;
};
export const RecapListViewTableColumns = () => {
  const base: any[] = [
    {
      Header: "NO",
      id: "seqNo",
      accessor: "seqNo",
      minWidth: 10,
      width: 40,
      maxWidth: 300,
      sort: false,
      type: "text",
      className: "text-center",
      disabled: true,
    },
    {
      Header: "DATE",
      accessor: "dtsDate",
      Cell: ({ value }: any) => formatYYYYMMDD(value),
      sort: true,
      minWidth: 40,
      width: 80,
      maxWidth: 1000,
      type: "text",
      className: "text-center",
    },
    {
      Header: "SEQ",
      accessor: "dtsSeq",
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      sort: true,
      minWidth: 20,
      width: 50,
      maxWidth: 1000,
      type: "text",
      className: "text-center",
    },
    {
      Header: "WORKER",
      accessor: "userNm",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 100,
      maxWidth: 1000,
      type: "text",
      className: "text-center",
    },
    {
      Header: "BUYER",
      accessor: "nmBuyer",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 100,
      maxWidth: 1000,
      type: "text",
    },
    {
      Header: "BRAND",
      accessor: "nmBrand",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 100,
      maxWidth: 1000,
      type: "text",
    },
    {
      Header: "YEAR",
      accessor: "dtsYear",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 80,
      maxWidth: 1000,
      type: "text",
      className: "text-center",
    },
    {
      Header: "SEASON",
      accessor: "nmSeason",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 80,
      maxWidth: 1000,
      type: "text",
      className: "text-center",
    },
    {
      Header: "TOPIC",
      accessor: "topic",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 100,
      maxWidth: 1000,
      type: "text",
    },
    {
      Header: "REMARK",
      accessor: "remark",
      sort: true,
      Cell: ({ value }: { value: any }) => <span style={{ fontWeight: "normal" }}>{value}</span>,
      minWidth: 40,
      width: 100,
      maxWidth: 1000,
      type: "text",
    },
  ];
  return base;
};
