export const UserRegisterFormFields = [
  {
    label: "사용자 ID (사번)",
    type: "text",
    placeholder: "사용자 ID 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null, // 아이콘 없음
  },
  {
    label: "사원 번호",
    type: "text",
    placeholder: "사원 번호 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: "ti-search", // 아이콘 추가
  },
  {
    label: "사용자명 (한글)",
    type: "text",
    placeholder: "사용자명 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "사용자명 (영문)",
    type: "text",
    placeholder: "영문명 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "비밀번호",
    type: "password",
    placeholder: "비밀번호 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "비밀번호 (확인)",
    type: "password",
    placeholder: "비밀번호 확인",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "전화번호",
    type: "text",
    placeholder: "전화번호 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "H.P(MOBILE)",
    type: "text",
    placeholder: "모바일 번호 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "사업장",
    type: "select",
    options: [
      { value: "1000", label: "(주)팬코 본사" },
      { value: "3000", label: "팬코빈증" },
      { value: "5000", label: "팬코꽝남" },
      { value: "6000", label: "팬코미얀마" },
      { value: "7000", label: "팬코바고" },
      { value: "8000", label: "호치민오피스" },
    ],
    labelClass: "custom-label-class",
    col: 7,
    iClass: null,
  },
  {
    label: "거래처코드 (SCM)",
    type: "text",
    placeholder: "거래처 코드",
    labelClass: "custom-label-class",
    col: 6,
    iClass: "ti-search",
  },
  {
    label: "사용자 구분",
    type: "select",
    options: ["일반사용자", "SCM사용자", "관리자"],
    labelClass: "custom-label-class",
    col: 6,
    iClass: "mdi mdi-chevron-down", // 아이콘 추가
  },
  {
    label: "Email(1)",
    type: "email",
    placeholder: "Email 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "Email(2)",
    type: "email",
    placeholder: "추가 Email 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  { label: "사용 시작일", type: "date", labelClass: "custom-label-class", col: 6, iClass: null },
  { label: "사용 종료일", type: "date", labelClass: "custom-label-class", col: 6, iClass: null },
  {
    label: "참고사항",
    type: "textarea",
    placeholder: "참고사항 입력",
    labelClass: "custom-label-class",
    col: 12,
    iClass: null,
  },
  {
    label: "게스트 여부",
    type: "radio",
    options: ["Yes", "No"],
    labelClass: "custom-label-class",
    col: 12,
    iClass: null,
  },
  {
    label: "회사명",
    type: "text",
    placeholder: "회사명 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "부서",
    type: "text",
    placeholder: "부서 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
  {
    label: "직책",
    type: "text",
    placeholder: "직책 입력",
    labelClass: "custom-label-class",
    col: 6,
    iClass: null,
  },
];
